sudo: required
dist: trusty
language: csharp

before_install:
  - sudo add-apt-repository --yes ppa:avsm/ppa
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository --yes ppa:0k53d-karl-f830m/openssl
  - sudo apt-get -qq update

install:
  - sudo apt-get install --yes libssl-dev opam libsqlite3-dev libgmp-dev
  - export OPAMYES=true
  - opam init
  - eval $(opam config env)
  - opam install batteries sqlite3 fileutils stdint zarith yojson
  - export Z3=z3-4.4.1-x64-ubuntu-14.04
  - wget https://github.com/Z3Prover/z3/releases/download/z3-4.4.1/$Z3.zip
  - unzip $Z3.zip
  - export PATH=/home/travis/build/mitls/mitls-fstar/$Z3/bin:/home/travis/build/mitls/mitls-fstar/.fstar/bin:$PATH
  - ocamlfind ocamlopt -config

script:
  - ./scripts/travis.sh
  - make -C .fstar/src/ocaml-output
  - make -C src/tls -k all-ver
  - make -C src/tls tls-ffi

notifications:
  slack:
    rooms:
      # Regenerate with `travis encrypt "everestexpedition:<token>#mitls-travis-build"`
      # where <token> comes from the Travis CI settings at https://everestexpedition.slack.com/services/
      secure: dG9lvoeKxFVEVGApx8eGfXS8vunDu4h6SWMwE4EFms5vLgclCS7/hixn07y1OX7BypUOOc4DHK9hOYvEuDE1YoM47bBkmEQOW5CxQmId73shMSmRcmBgsX/clXJv5d6eTQcRu8hsvIW/IMYJGeQQH0P+p4Cxck+6Dve5lgDF19WthVS79C/3z17a2fGYegnTX4gI1oRlCfQmrrs6UcK+yJfUn/gXrHj3fMsXxwPIcuEF2L5aG5kIBk5JbUVmj9N25pBNO1w9n+8ysXk3GS9HlPzNctTT9R9PybPBdU7VfdWXwTErLAKCQTOU0ZBgoFSMhnZenOOPuEnL+AIVfCJogOb7auStUCvBWjwYHzk/wZ9SL7+RMMc0LmA+ODvNow6bYpinQuG8pWrGvz3Y8vAnt/zYNNvXPbJsX2PinfwrDehEr7EJegiXpo0f30nT1CoU+xU427lBKPBh8bEGmW1wMkGrExQGEwtxxIMoWcx1UYx/5boToLNdksH9YJ8j1VEUNMhZEwcYwApDKk9BKx9YIUsGPgElEF7q4BhaprW7srduvHhw2xbWAHfV01xN2lg/GzWhSoQuNWF0RTJVtR81kKSLF/eFsb/Smpeo6eqYlgI6JY955C+MA+ex8G+8gOpWS8kJwImfYYVXazSV7XJ/XtVC0Zd0A3r2UQG8BtbtGIk=

git:
    depth: 3
